use_frameworks!

platform :ios, '9.0'

target 'TestAppTool_Example' do
  pod 'TestAppTool', :path => '../'

  target 'TestAppTool_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
